include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [ test/**.mocks.dart, lib_old/**.dart, test_old/**.dart ]
  language:
    strict-casts: false
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: false
    prefer_if_null_operators: false
    lines_longer_than_80_chars: false
    prefer_const_constructors_in_immutables: false
    use_build_context_synchronously: false
    cast_nullable_to_non_nullable: false
    sort_constructors_first: false
    avoid_dynamic_calls: false
    flutter_style_todos: false
    require_trailing_commas: true
    prefer_single_quotes: true
    prefer_final_fields: true
    prefer_final_parameters: true
    always_specify_types: true
   