name: web_personal_finances
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.4.0
  flutter_dotenv: ^6.0.0
  firebase_auth: ^6.1.4
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  equatable: ^2.0.5
  internationalization: ^5.0.0
  shared_preferences: ^2.1.1
  go_router: ^17.1.0
  flutter_svg: ^2.0.17
  flutter_side_menu: ^0.5.41
  http: ^1.0.0
  fl_chart: ^1.1.1
  lottie: ^3.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cloud_firestore: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/translations/
    - assets/animations/
