// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL7CwOGIk0m46rNU7z_vLF2eLrmVN4p8E',
    appId: '1:750329225286:web:44e078c8de16df397c2a47',
    messagingSenderId: '750329225286',
    projectId: 'web-personal-finances',
    authDomain: 'web-personal-finances.firebaseapp.com',
    storageBucket: 'web-personal-finances.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB70SQ09HeMVeg6nRoDxebQ8ATXBzGqLyE',
    appId: '1:750329225286:android:73c06d0cc381541a7c2a47',
    messagingSenderId: '750329225286',
    projectId: 'web-personal-finances',
    storageBucket: 'web-personal-finances.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmSeeK74unKpADMCles62Uq5Ovl5se8oM',
    appId: '1:750329225286:ios:d90e2a45354ef0d97c2a47',
    messagingSenderId: '750329225286',
    projectId: 'web-personal-finances',
    storageBucket: 'web-personal-finances.firebasestorage.app',
    iosBundleId: 'com.example.webPersonalFinances',
  );
}
